// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgaefahmwxtosvjstghz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYWVmYWhtd3h0b3N2anN0Z2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTcyMTksImV4cCI6MjA2ODk5MzIxOX0.1QPV_z0mRfgBCOWp5n4UE3g812N-SaCtlFkKtTnUw1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});